language : scala

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 "project fs2-zk" test


